name: HDLogin
main: com.hdlogin.HDLoginPlugin
version: 1.0
api-version: 1.8

description: 一个简单的登录插件，要求玩家注册或登录后才能与服务器交互
authors: [hdiask]
website: 

commands:
  slogin:
    description: HDLogin主命令
    usage: /slogin [reload]
    permission: hdlogin.user
    permission-message: 你没有权限使用此命令
  login:
    description: 登录你的账号
    usage: /login <密码>
    permission: hdlogin.user
    permission-message: 你没有权限使用此命令
  register:
    description: 注册新账号
    usage: /register <密码>
    permission: hdlogin.user
    permission-message: 你没有权限使用此命令
  changepassword:
    description: 更改密码
    usage: /changepassword <旧密码> <新密码>
    permission: hdlogin.user
    permission-message: 你没有权限使用此命令
  unregister:
    description: 注销账号
    usage: /unregister
    permission: hdlogin.user
    permission-message: 你没有权限使用此命令
  unloginban:
    description: 解除玩家的登录封禁
    usage: /unloginban <玩家名>
    permission: hdlogin.admin
    permission-message: 你没有权限使用此命令
  forcelogin:
    description: 强制让玩家登录或注册
    usage: /forcelogin <玩家名>
    permission: hdlogin.admin
    permission-message: 你没有权限使用此命令

permissions:
  hdlogin.*:
    description: 所有HDLogin权限
    children:
      hdlogin.admin: true
      hdlogin.user: true
  hdlogin.admin:
    description: 管理员权限
    default: op
    children:
      hdlogin.unloginban: true
      hdlogin.forcelogin: true
  hdlogin.user:
    description: 普通用户权限
    default: true
    children:
      hdlogin.login: true
      hdlogin.register: true
      hdlogin.changepassword: true
      hdlogin.unregister: true
  hdlogin.login:
    description: 使用登录命令
    default: true
  hdlogin.register:
    description: 使用注册命令
    default: true
  hdlogin.changepassword:
    description: 使用更改密码命令
    default: true
  hdlogin.unregister:
    description: 使用注销命令
    default: true
  hdlogin.unloginban:
    description: 使用解除封禁命令
    default: op
  hdlogin.forcelogin:
    description: 使用强制登录命令
    default: op